language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

# Install dependencies
install:
  - pip install -r requirements.txt
  - pip install flake8 pytest

# Run tests
script:
  - flake8
  - pytest -v
